
import React, { useState } from 'react';
import { XIcon } from './Icons.tsx';

interface ComplianceModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'privacy' | 'terms';
}

const ComplianceModal: React.FC<ComplianceModalProps> = ({ isOpen, onClose, type }) => {
  const [lang, setLang] = useState<'EN' | 'KR'>('EN');

  if (!isOpen) return null;

  const content = {
    privacy: {
      EN: {
        title: "Privacy Policy",
        body: `
Last Updated: May 2026

1. DATA COLLECTION & AI PROCESSING
This site utilizes the Google Gemini API to power the "Idea Explorer" and "AI Assistant." When you input text, it is sent to Google for transient processing. We do not store your chat history on our servers; however, information provided to the AI should not contain sensitive personal student data or PII (Personally Identifiable Information).

2. VOLUNTARY INFORMATION
If you choose to contact Jason Benjamin via email or feedback forms, we collect your name and email address solely to respond to your inquiry. This data is never sold, traded, or shared with third-party advertisers.

3. COOKIES & TRACKING
We strive for a "cookieless" experience. We may use basic, privacy-respecting analytics to understand which projects are most interesting to our visitors, but we do not track you across other websites.

4. STUDENT PRIVACY (COPPA/FERPA)
As a tool built by a teacher, we take student privacy seriously. Our tools are designed to be "privacy-by-design." We encourage teachers to use anonymized data (e.g., "Student A" instead of "John Doe") when testing our beta tools.

5. CONTACT
For any privacy-related questions or data deletion requests, please contact: jsn.benjamin@gmail.com
        `
      },
      KR: {
        title: "개인정보 처리방침",
        body: `
최종 수정일: 2026년 5월

1. 데이터 수집 및 AI 처리
본 사이트는 '아이디어 익스플로러(Idea Explorer)' 및 'AI 어시스턴트' 기능을 위해 Google Gemini API를 사용합니다. 귀하가 입력한 텍스트는 일시적인 처리를 위해 Google로 전송됩니다. 당사는 귀하의 채팅 기록을 서버에 저장하지 않으나, AI에 민감한 학생 개인정보나 개인식별정보(PII)를 입력하지 마십시오.

2. 자발적 정보 제공
이메일이나 피드백 양식을 통해 Jason Benjamin에게 연락하는 경우, 귀하의 성함과 이메일 주소는 문의 응대 목적으로만 수집됩니다. 이 데이터는 제3자 광고주에게 판매, 거래 또는 공유되지 않습니다.

3. 쿠키 및 추적
당사는 '쿠키 없는(cookieless)' 환경을 지향합니다. 방문자가 어떤 프로젝트에 관심을 갖는지 파악하기 위해 기본적인 분석 도구를 사용할 수 있으나, 다른 웹사이트에서의 활동을 추적하지는 않습니다.

4. 학생 정보 보호 (COPPA/FERPA 준수)
교사가 직접 만든 도구로서, 당사는 학생의 프라이버시를 매우 중요하게 생각합니다. 모든 도구는 '프라이버시 중심 설계'를 원칙으로 합니다. 베타 도구를 테스트할 때 학생의 실명 대신 익명(예: '학생 A')을 사용하실 것을 권장합니다.

5. 문의처
개인정보 관련 문의 또는 데이터 삭제 요청: jsn.benjamin@gmail.com
        `
      }
    },
    terms: {
      EN: {
        title: "Terms of Service",
        body: `
Last Updated: May 2026

1. BETA/MVP DISCLOSURE
The projects showcased here (Chekki AI, Benchmark Explorer, EduPlanner, etc.) are currently in Public Beta or MVP (Minimum Viable Product) status. They are provided "AS IS" and "AS AVAILABLE" without any warranties, express or implied.

2. AI GENERATED CONTENT
The "Idea Explorer" provides conceptual suggestions generated by Artificial Intelligence. These suggestions are for inspirational purposes only and should be reviewed by qualified educational professionals before implementation in a real-world classroom setting.

3. INTELLECTUAL PROPERTY
The layout, design, and code of this portfolio are the property of Jason Benjamin. You are granted a limited license to explore and test the tools for personal or professional evaluation. Commercial redistribution of these tools is strictly prohibited without written consent.

4. LIMITATION OF LIABILITY
In no event shall the developer be liable for any data loss, scheduling conflicts, or educational outcomes resulting from the use of these beta tools. Use at your own discretion and risk.

5. USER CONDUCT
Users agree not to use the AI Assistant or tools to generate harmful, illegal, or offensive content. We reserve the right to limit access to anyone violating these terms.
        `
      },
      KR: {
        title: "이용 약관",
        body: `
최종 수정일: 2026년 5월

1. 베타/MVP 공개 고지
본 포트폴리오에 소개된 프로젝트(Chekki AI, Benchmark Explorer, EduPlanner 등)는 현재 공개 베타 또는 MVP(최소 기능 제품) 단계에 있습니다. 본 서비스는 명시적 또는 묵시적인 보증 없이 "있는 그대로" 그리고 "이용 가능한 상태로" 제공됩니다.

2. AI 생성 콘텐츠
'아이디어 익스플로러'는 인공지능이 생성한 개념적 제안을 제공합니다. 이러한 제안은 영감을 주기 위한 목적일 뿐이며, 실제 교실 현장에 적용하기 전에는 반드시 자격 있는 교육 전문가의 검토를 거쳐야 합니다.

3. 지적 재산권
본 포트폴리오의 레이아웃, 디자인 및 코드는 Jason Benjamin의 자산입니다. 귀하에게는 개인적 또는 전문가적 평가 목적으로 본 도구를 탐색하고 테스트할 수 있는 제한적인 권한이 부여됩니다. 서면 동의 없는 상업적 재배포는 엄격히 금지됩니다.

4. 책임의 제한
개발자는 본 베타 도구의 사용으로 인해 발생하는 데이터 손실, 일정 충돌 또는 교육적 결과에 대해 어떠한 경우에도 책임을 지지 않습니다. 모든 사용은 귀하의 판단과 책임 하에 이루어집니다.

5. 사용자 준수 사항
사용자는 AI 어시스턴트나 도구를 사용하여 유해하거나 불법적이거나 공격적인 콘텐츠를 생성하지 않을 것에 동의합니다. 당사는 본 약관을 위반하는 사용자의 접근을 제한할 권리를 보유합니다.
        `
      }
    }
  };

  const activeContent = content[type][lang];

  return (
    <div className="fixed inset-0 z-[110] flex items-center justify-center p-6 md:p-12">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-md" onClick={onClose}></div>
      <div className="relative w-full max-w-2xl glass-panel rounded-[2rem] overflow-hidden flex flex-col max-h-[80vh]">
        {/* Header */}
        <div className="p-8 border-b border-white/10 flex justify-between items-center bg-alpine-950/50">
          <div className="flex items-center gap-6">
            <h2 className="text-2xl font-light text-white font-display tracking-tight uppercase">
              {activeContent.title}
            </h2>
            <div className="flex bg-white/5 rounded-full p-1 border border-white/10">
              <button 
                onClick={() => setLang('EN')}
                className={`px-3 py-1 rounded-full text-[10px] font-bold transition-all ${lang === 'EN' ? 'bg-accent-gold text-alpine-950' : 'text-white/40 hover:text-white'}`}
              >
                EN
              </button>
              <button 
                onClick={() => setLang('KR')}
                className={`px-3 py-1 rounded-full text-[10px] font-bold transition-all ${lang === 'KR' ? 'bg-accent-gold text-alpine-950' : 'text-white/40 hover:text-white'}`}
              >
                KR
              </button>
            </div>
          </div>
          <button onClick={onClose} className="p-2 text-white/40 hover:text-white transition-all">
            <XIcon className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8 md:p-12 space-y-6 text-white/60 font-light text-sm leading-relaxed whitespace-pre-wrap">
          {activeContent.body}
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-white/10 text-center bg-alpine-950/50">
          <button 
            onClick={onClose}
            className="text-[10px] font-bold uppercase tracking-[0.3em] text-accent-gold hover:text-white transition-all"
          >
            I UNDERSTAND
          </button>
        </div>
      </div>
    </div>
  );
};

export default ComplianceModal;
